### ISSUE TITLE
Harmonize analysis views

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CO2AnalysisModules#15]

**Comment by siirtola** [comment]
Ensure all visualization views follow the structure: **COHORTS-FILTERS-DATA**. Within the **DATA** section, divide content into multiple panes as necessary, with the minimum being "Plot" and "Table". The **Table** view will display the raw data in an interactive format that can be manipulated, while the **Plot** view(s) will feature interactive visualizations of the data. All views should include a "Download" button, allowing users to export data as a CSV file or the visualizations as a PDF.

### General Issues
- The "About" pages need to be completed. A draft for the "Cohort Overlaps" section is available.
- The "About" page could serve as a brief user manual. Could you review the draft and provide feedback?

### Cohort Demographics
- Are additional types of visualizations needed for the demographics section?

### Cohort Overlaps
- Should we include any other types of visualizations for overlaps?

### TimeCodeWAS
- The **Plot** view still uses `ggiraph` to overlay lines on a `ggplot` image. While all known issues have been resolved, this could potentially break if there are updates to `ggiraph`, `ggplot2`, or grid graphics.
- In the **Table** view, should the OR and p-value columns be placed side by side?
- The table is currently sorted in ascending order by p-value. Should it be sorted by both (p, OR)?

### CodeWAS
- The visualization view has not been implemented yet.
- Should there be more than one type of visualization, such as a Manhattan plot and a Volcano plot?
